= polymatic

The `polymatic` library contains routine "polynomial" or "multiprecision" arithmetic with integer coefficients.

This is an educational project with the purpose of learning and sharing algorithmic mathematics.

This library is defined in a C++23 module.

Building the library requires these tools.

- clang 20+
- ninja 1.11+
- cmake 3.30+

To build the library:

[source,shell]
----
cmake --preset default
cmake --build --preset default
----

To test the library:

[source,shell]
----
cmake-build-default/polymatic-test
----

`polymatic-test` is a Google Test program containing unit tests for the library.

Fuzzying the library requires these tools.

- GNU bc

To fuzz the `square` routine with a 8 degree "poly" 1000 times:

[source,shell]
----
cmake-build-default/polymatic-fuzz square 8 1000 </dev/random | tee log | bc | cmake-build-default/polymatic-fuzz assert-zero
----

If successful, this pipeline prints nothing and returns `0`. Else, it prints the index of the failed case, whose parameters can be found in the `log` file.

`polymatic-fuzz square` prints a program for `GNU bc` whose expressions must always return `0`. If any expressions return a different value, that means the routine produced the wrong value.

`polymatic-fuzz assert-zero` consumes numbers from the standard input and tests for zero. If nonzero, it prints the index of this number and returns nonzero.