= purple-arithmetic
:author: Pedro Lamarão <pedro.lamarao@gmail.com>

The `purple-arithmetic` library contains procedures for arithmetics with "long" integers.

This is an educational project with the purpose of learning and sharing algorithmic mathematics.

This library is defined in a C++26 module.

References:

* Donald E. Knuth, "The Art of Computer Programming", volume 2, "Seminumerical Algorithms", third edition, ISBN 0-201-89684-2
* MMIXmasters, "MIX to MMIX Conversion", https://mmix.cs.hm.edu/mmixmasters/index.html#MIXtoMMIX
* Alexander Stepanov, Paul McJones, "Elements of Programming", Addison-Wesley, 2009, ISBN 978-0-321-63537-2
* Alexander Stepanov, Daniel Rose, "From Mathematics to Generic Programming", Addison Wesley, 2015, ISBN 978-0-321-94204-3
* Niels Möller, Torbjörn Granlund, "Improved division by invariant integers"

Building the library requires these tools.

- clang 20+
- ninja 1.11+
- cmake 3.30+

To build the library:

[source,shell]
----
cmake --preset default
cmake --build --preset default
----

To test the library, run the `purple-arithmetic-test` program.

[source,shell]
----
cmake-build-default/purple-arithmetic-test
----

`purple-arithmetic-test` is a Google Test program containing unit tests for the library.

To fuzz procedures, use the `purple-arithmetic-fuzz` program.

To fuzz the `square` procedure 1000 times with 8-word numbers:

[source,shell]
----
cmake-build-default/purple-arithmetic-fuzz square 8 1000
----

Each iteration, the fuzzer generates random numbers, computes both with purple-arithmetic and GMP, and prints a report. If a difference is found, the fuzzer terminates with status 1.

Available fuzzers:

* `difference-restricted` _degree_ _iterations_
* `division-2-1` _iterations_
* `division-N-1` _iterations_
* `half` _degree_ _iterations_
* `product` _degree_ _iterations_
* `product-N-1` _degree_ _iterations_
* `square` _degree_ _iterations_
* `sum` _degree_ _iterations_
* `twice` _degree_ _iterations_
