= purple-arithmetic
:author: Pedro Lamarão <pedro.lamarao@gmail.com>
:lang: pt

For this text in english, see link:README.adoc[].

A biblioteca `purple-arithmetic` contém rotinas para aritmética com inteiros não-negativos "grandes".

Este é um projeto educacional com o propósito de aprendizado e compartilhamento de matemática algorítmica.

Esta biblioteca está definida em um módulo C++26.

Referências:

* Donald E. Knuth, "The Art of Computer Programming", volume 2, "Seminumerical Algorithms", third edition, ISBN 0-201-89684-2
* MMIXmasters, "MIX to MMIX Conversion", https://mmix.cs.hm.edu/mmixmasters/index.html#MIXtoMMIX
* Alexander Stepanov, Paul McJones, "Elements of Programming", Addison-Wesley, 2009, ISBN 978-0-321-63537-2
* Alexander Stepanov, Daniel Rose, "From Mathematics to Generic Programming", Addison Wesley, 2015, ISBN 978-0-321-94204-3
* Niels Möller, Torbjörn Granlund, "Improved division by invariant integers", IEEE Transactions on Computers, Volume 60, Issue 2, February 2011, DOI: 10.1109/TC.2010.143

Construir a biblioteca exige estas ferramentas.

- clang 20+
- ninja 1.11+
- cmake 3.30+

Para construir a biblioteca:

[source,shell]
----
cmake --preset default
cmake --build --preset default
----

Para testar a qualidade, execute o programa `purple-arithmetic-test`.

[source,shell]
----
cmake-build-default/purple-arithmetic-test
----

Este é um programa padrão do Google Test, aceitando as opções de linha de comando convencionais.

Para testar o desempenho, execute o programa `purple-arithmetic-bechmark`.

[source,shell]
----
cmake-build-default/purple-arithmetic-benchmark
----

Este é um programa padrão Google Benchmark, aceitando as opções de linha de comando convencionais.

O desempenho será comparado contra a biblioteca GMP.