= purple-arithmetics
:author: Pedro Lamarão <pedro.lamarao@purpura.dev.br>
:icons: font
:lang: pt

For this text in english, see link:README.adoc[].

A biblioteca `purple-arithmetics` contém rotinas para aritmética com inteiros não-negativos "longos".

Este é um projeto educacional com o propósito de aprendizado e compartilhamento de matemática algorítmica.

Esta biblioteca está definida como um módulo C++26 em link:main/ixx[].

Referências:

* Donald E. Knuth, "The Art of Computer Programming", volume 2, "Seminumerical Algorithms", third edition, ISBN 0-201-89684-2
* MMIXmasters, "MIX to MMIX Conversion", https://mmix.cs.hm.edu/mmixmasters/index.html#MIXtoMMIX
* Peter Montgomery, Torbjörn Granlund, "Division by Invariant Integers using Multiplication", PLDI '94, DOI: 10.1145/178243.178249
* Alexander Stepanov, Paul McJones, "Elements of Programming", Addison-Wesley, 2009, ISBN 978-0-321-63537-2
* Niels Möller, Torbjörn Granlund, "Improved division by invariant integers", IEEE Transactions on Computers, Volume 60, Issue 2, February 2011, DOI: 10.1109/TC.2010.143
* Alexander Stepanov, Daniel Rose, "From Mathematics to Generic Programming", Addison Wesley, 2015, ISBN 978-0-321-94204-3

Construir a biblioteca exige estas ferramentas.

- clang 20+
- libstdc++ 14+
- ninja 1.11+
- cmake 3.30+

Para construir a biblioteca:

[source,shell]
----
cmake --preset default
cmake --build --preset default
----

Para testar a qualidade, execute o programa `purple-arithmetics-test`.

[source,shell]
----
cmake-build-default/test/purple-arithmetics-test
----

Este é um programa padrão do Google Test, aceitando as opções de linha de comando convencionais.

Para testar o desempenho, execute o programa `purple-arithmetics-bechmark`.

[source,shell]
----
cmake-build-default/benchmark/purple-arithmetics-benchmark
----

Este é um programa padrão Google Benchmark, aceitando as opções de linha de comando convencionais.

O desempenho será comparado contra a biblioteca GMP.